apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSetInputProvider
metadata:
  name: victoria-logs-platform-sandbox
  namespace: flux-system
  labels:
    app: victoria-logs
spec:
  type: Static
  defaultValues:
    version: "0.13.9"
