apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSetInputProvider
metadata:
  name: otel-collector-platform-sandbox
  namespace: flux-system
  labels:
    app: otel-collector
spec:
  type: Static
  defaultValues:
    version: "0.168.0"
