apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSetInputProvider
metadata:
  name: metrics-server-platform-sandbox
  namespace: flux-system
  labels:
    app: metrics-server
spec:
  type: Static
  defaultValues:
    version: "3.13.1"
