apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSetInputProvider
metadata:
  name: tempo-app-dev
  namespace: flux-system
  labels:
    app: tempo
spec:
  type: Static
  defaultValues:
    version: "1.24.4"
