apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSet
metadata:
  name: istio-gateway
  namespace: flux-system
  annotations:
    fluxcd.controlplane.io/reconcile: "enabled"
    fluxcd.controlplane.io/reconcileEvery: "30m"
    fluxcd.controlplane.io/reconcileTimeout: "5m"
    fluxcd.controlplane.io/force: "true"
spec:
  wait: true
  inputsFrom:
    - kind: ResourceSetInputProvider
      selector:
        matchLabels:
          app: istio
  dependsOn:
    - apiVersion: fluxcd.controlplane.io/v1
      kind: ResourceSet
      name: istio
      namespace: flux-system
      ready: true
    - apiVersion: fluxcd.controlplane.io/v1
      kind: ResourceSet
      name: cert-manager-ca-issuer
      namespace: flux-system
      ready: true
  resources:
    - apiVersion: cert-manager.io/v1
      kind: Certificate
      metadata:
        name: wildcard-tls
        namespace: istio-system
      spec:
        secretName: wildcard-tls
        duration: 2160h # 90 days
        renewBefore: 360h # 15 days
        commonName: "<< inputs.domain >>"
        dnsNames:
          - "<< inputs.domain >>"
          - "*.<< inputs.domain >>"
        issuerRef:
          name: ca-issuer
          kind: ClusterIssuer
    - apiVersion: networking.istio.io/v1
      kind: Gateway
      metadata:
        name: gateway
        namespace: istio-system
      spec:
        selector:
          istio: ingressgateway
        servers:
        - port:
            number: 443
            name: https
            protocol: HTTPS
          tls:
            mode: SIMPLE
            credentialName: wildcard-tls
          hosts:
          - "*.<< inputs.domain >>"
    - apiVersion: networking.istio.io/v1
      kind: VirtualService
      metadata:
        name: grafana
        namespace: monitoring
      spec:
        hosts:
          - "grafana.<< inputs.domain >>"
        gateways:
          - istio-system/gateway
        http:
          - route:
              - destination:
                  host: kube-prometheus-stack-grafana.monitoring.svc.cluster.local
                  port:
                    number: 80
