apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSetInputProvider
metadata:
  name: cert-manager-platform-sandbox
  namespace: flux-system
  labels:
    app: cert-manager
spec:
  type: Static
  defaultValues:
    version: "v1.21.0"