apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base/istio
  - ../base/cert-manager
  - ../base/opa
  - ../base/team-namespaces
  - istio.yaml
  - cert-manager.yaml
  - opa.yaml

patches:
  - path: team-namespaces.yaml
    target:
      kind: ResourceSet
      name: team-namespaces

labels:
  - pairs:
      env: platform-sandbox
    includeSelectors: true
    includeTemplates: true