apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token-secret
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:n3Eio/VHPf6myA7UyHtSNHeQEleVkzeTLvmk3doh1zW3z/RUNc3CHQ==,iv:Ja1jazG7uQLl2x4TxTUPDaOKtt6ZuRCeKCVaiWAVWMM=,tag:5AlastBEWJaLZadnTiH62Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAycmhBakdsOExoSGpCcW81
            cUhaQ2kvTENDcEtqRk1pT1ZQTkVkRUpDQlVzCk1pM2xaN3FOSFFVSnFkVWlKTzEz
            VkxqQ1Y3a3BPVlZXUXc3OXAzTGRmMmcKLS0tIGdGaU8wSWtGSFMrR1RWSENwR0Zx
            T2RBZlZLU3BJYStlNlFFRDVIRlpPb28KAHImCtL4rY6XJU64dk6PACeCOFFvMmIN
            kpch4zfGwX+oxB7jaAkWB0Ux//qD/fMbeqYfxTfF6RGN/MmlBzfUpQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1z0se3h2fc40uflwhgeg88szw8qyyuesd9rsxfe962e8pa2t6zaxq5ttmsg
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-07T19:23:12Z"
    mac: ENC[AES256_GCM,data:jWpqT3omPgB00kQaD35UYxz/yBimi91s114s9e+REzmPrnJpcs9FxxKq6dzrWciFgGYK9fxkmBPx8fYv/P9FkyJcnBfKyJxFKqycq1wROGshD0/Yj0Y0u26AJlpMJkzEi50ITX9ZnSudJIzRHHQPkLkMayvuk9KS2CHiiYFGCnU=,iv:dQFl5/kb8+PfYIBsJWMReu45RNmv6wy27lvRjGsz6qM=,tag:6euNM7n9R5CzIjYLfDAJhQ==,type:str]
    version: 3.13.3
