apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token-secret
    namespace: cert-manager
type: Opaque
data:
    api-token: ENC[AES256_GCM,data:KJP9oPGfCXVQCTePofN1luXtNwIgmmOX0C6Jn+tESQ/7NTwdBuEXXQ==,iv:8apIpcST5CL8YEkwFegHKzhnyjKCHxJh66eFK/iG5F4=,tag:x86G4Jn1DsTxdW2fR85R6Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPakMySFpHMERrRU1hdWtR
            ZFJWUXd6UGd1YnRVRkFEOVZPUUlIVWxBSXo4CnRnT1QrcDRleVVqcndyV3AzWklu
            a3l2cEhkN1hBZDZybG1BNlphSXJCRDQKLS0tIDJzRURVMVRmNkVxNnMyWmJUbTEw
            TjJNdCsyM0JyMytscTBvRTlkZlhkdzQKriZ3ZzY6cCHDfRtsxeddQe/xajT3YVLD
            YTKdROTKAtiZieKNehk9H84QBuX96YynjunRDDBGU2mUxFE9VpVgkQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1z0se3h2fc40uflwhgeg88szw8qyyuesd9rsxfe962e8pa2t6zaxq5ttmsg
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-07T19:20:34Z"
    mac: ENC[AES256_GCM,data:J+26WcqyFIFi3kJgnD1TH2Mt+BFNi1uF5z2PTLuY/N9qP+mtLqWVEBZEd0EP+kTP0jbasEdNjqdg2xJU6pjIrKIyynECupEGyE8j+lHpp+Tors5w0vN5X0CkRk3lvMGc99W7+vwO7tixD2duvreDOAvnfdiX/ySjMD5uH/8zSNc=,iv:yquM2yhyw8h3gaLwXaFcXaLVE6jXyoZHJ3N8N/mI7LY=,tag:HmUjLYaxJD96rwv1xiCqVw==,type:str]
    version: 3.13.3
