apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base/istio
  - ../base/team-namespaces
  - istio.yaml

patches:
  - path: team-namespaces.yaml
    target:
      kind: ResourceSet
      name: team-namespaces

labels:
  - pairs:
      env: app-dev
    includeSelectors: true
    includeTemplates: true