apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base/istio
  - ../base/cert-manager
  - ../base/opa
  - ../base/team-namespaces
  - ./istio
  - ./cert-manager
  - ./opa

patches:
  - path: team-namespaces/patch.yaml
    target:
      kind: ResourceSet
      name: team-namespaces

labels:
  - pairs:
      env: app-dev
    includeSelectors: true
    includeTemplates: true